version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment: 
      - JENKINS_OPTS="--httpPort=8888"
    privileged: true
    user: root
    ports:
      - 8888:8888
      - 50000:50000 
    volumes:
      - /var/lib/docker/volumes/jenkins/_data:/var/jenkins_home
      - /var/lib/docker/volumes/jenkins/_data/root:/root
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - /var/lib/docker/volumes/prometheus/_data/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - /var/lib/docker/volumes/jenkins/_data/grafana/:/var/lib/grafana
      - /var/lib/docker/volumes/jenkins/_data/grafana/provisioning/:/etc/grafana/provisioning/
